### ISSUE TITLE
Check the split files

### ISSUE THREAD

**Issue by vytautasBrundza** [VerifiedToken/bem-token#15]
Hi Marfat,

Could you please go through the split-partials branch and check if I split files correctly. Please give some feedback about best practices of partitioning code.

Thanks, Vito

**Comment by VerifiedMarfat** [comment]
The head.php partial should not include the DOCTYPE declaration as it will be mean that the HTML opening tag and closing tag will be in two different files. This is not very desirable. Each partial should be almost standalone files.

We should have at least the following partials:
- Head (includes all the content INSIDE head tag)
- Footer 
- Splash

I would rename the index.php file to shop.php so we can have different files for each page. Whenever there is something that we copy and paste from a page, we create a partial for it so we only need to make a change to it once.

**Comment by VerifiedMarfat** [comment]
Merged into develop.
