### ISSUE TITLE
Search button mis-positioned

### ISSUE THREAD

**Issue by vytautasBrundza** [VerifiedToken/bem-token#5]
There is a small gap appearing sometimes when resizing the page
<img width="338" alt="screenshot 2015-09-24 19 34 30" src="https://cloud.githubusercontent.com/assets/9215624/10082799/7c27b64a-62f3-11e5-9347-f8fb6bd86adb.png">

**Comment by VerifiedMarfat** [comment]
Fix available in branch: feature/search-input-fix-ff
